version: "3.7"
services:
    web:
        image: httpd
        ports:
            - "80:80"
        links:
            - db
        volumes:
            - ./app:/app

    db:
        image: mariadb
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: database
        ports:
            - "8889:3306"
